name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose up --build

    - name: Install dependencies
      run: |
        docker-compose exec -it app python -m pip install --upgrade pip
        docker-compose exec -it app pip install flake8
    - name: Test 
      run: docker-compose exec -it app python manage.py test
    - name: Analysing the code with flake8
      run: |
        docker-compose exec -it app flake8 --per-file-ignores="expensetracker/settings.py:E501"
